# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code


trigger:
    branches:
      include:
        - main

pool:
    name: Azure-Agent

variables:
    dockerHubNamespace: 'mohameddoda97'
    dockerRegistryServiceConnection: 'dockerhub-service-conn'
    buildId: $(Build.BuildId)

parameters:
  - name: environment
    type: string
    default: dev
    values:
      - dev
      - stagging
      - prod

stages:

- stage: CI
  displayName: CI stage
  jobs:
  - job: Lint
    displayName: Linting Backend
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'
        addToPath: true
    - script: |
        python3.9 -m venv .venv
        source .venv/bin/activate
        pip install flake8
        flake8 src/feedback_backend/app.py
      displayName: 'Run Linting'

  - job: Test
    dependsOn: Lint
    displayName: Unit Test Backend
    steps:
    - checkout: self
    - script: |
        python3.9 -m venv .venv
        source .venv/bin/activate
        export PYTHONPATH=$PYTHONPATH:$(Build.SourcesDirectory)/src
        pip install -r src/feedback_backend/requirements.txt
        pip install pytest
        pytest
      displayName: 'Run Unit Test'
      workingDirectory: $(Build.SourcesDirectory)

  - job: Build
    dependsOn: [Lint, Test]
    displayName: Build and Push
    steps:
    - checkout: self
    
    - task: Docker@2
      displayName: Build and Push Backend Image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(dockerHubNamespace)/feedback-backend
        command: 'buildAndPush'
        Dockerfile: 'src/feedback_backend/Dockerfile'
        tags: $(Build.BuildId)
        buildContext: '$(Build.SourcesDirectory)/src/feedback_backend'

    - task: Docker@2
      displayName: Build and Push Frontend Image
      inputs:
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(dockerHubNamespace)/feedback_frontend
        command: 'buildAndPush'
        Dockerfile: 'src/feedback_frontend/src/Dockerfile'
        tags: $(Build.BuildId)
        buildContext: '$(Build.SourcesDirectory)/src/feedback_frontend'

- stage: CD
  displayName: CD stage
  dependsOn: CI
  jobs:
  - deployment: DeployToEKS
    displayName: Deploy to EKS
    environment: ${{ parameters.environment }}
    strategy:
        runOnce:
            deploy:
                steps:
                - checkout: self
                - task: ReplaceTokens@5
                  inputs:
                    rootDirectory: '$(Build.SourcesDirectory)/k8s'
                    targetFiles: "**/*.yaml"
                    tokenPattern: custom
                    tokenPrefix: '${'
                    tokenSuffix: '}'
                    verbosity: detailed
                    escapeType: json

                - task: AWSShellScript@1
                  displayName: 'Login to EKS Cluster'
                  inputs:
                    awsCredentials: 'aws-eks-service-connection'   
                    regionName: 'us-east-1'
                    scriptType: 'inline'
                    inlineScript: |
                      echo "Logging in to EKS cluster"
                      aws eks update-kubeconfig \
                        --region us-east-1 \
                        --name eks-deployment-cluster

                - script: |
                    kubectl apply -f $(Build.SourcesDirectory)/k8s/ -n ${{ parameters.environment }}
                  displayName: 'Deploy to EKS with kubectl'
